moscow:
  resource: "@n3bKladrBundle/Controller/"
  type:     annotation

n3b_kladr_region:
  path: /kladr/region/{query}
  defaults: { _controller: kladr:getRegions }

n3b_kladr_street:
  path: /kladr/street/{region}/{query}
  defaults: { _controller: kladr:getStreets }
  requirements:
    region: \d{10,11}

n3b_kladr_ajax:
  path: /kladr
  defaults: { _controller: kladr:proceedAjax }

n3b_kladr_ems_to:
  path: /emsTo/{region}/{weight}
  defaults: { _controller: kladr:getEmsTo }
  requirements:
    region: \d{10,11}
    weight: ([0-9]+(\.[0-9]+)?)

n3b_kladr_adds_by_street_code:
  path: /adds_by_code/{code}
  defaults: { _controller: kladr:getAddsByCode, code: '000000000000000' }
  requirements:
    code: \d{15}
