services:
  request:
    synthetic:                      true
  kladr:
    class:      n3b\Bundle\Kladr\Service\Kladr
    arguments:
       - '@doctrine.orm.entity_manager'
       - '@request'

  ymaps_service:
     class:      n3b\Bundle\Kladr\Service\YMaps
     arguments:
        - '@service_container'